### PR TITLE
add Semi Icons StreamGeometry

### PR DESCRIPTION
**Pull request by zdpcdt**
image

### CODE REVIEW

**Comment by zdpcdt** [comment]
Would it be better to release the icons as a separate package?

**Comment by rabbitism** [comment]
Worth noting package size increase from 528kb to 677 kb

**Comment by rabbitism** [comment]
What is IconPatch file used for?

**Comment by rabbitism** [comment]
> What is IconPatch file used for?

Oh, I see, it seems to be a backward compat for typos?

**Review by rabbitism — APPROVED** [review]

**Pull request merged**
