### PR TITLE
ScrollViewer Update

### LINKED ISSUE #173: ScrollViewer 希望可以提供一个 滚动轴不需要鼠标悬浮也一直显示的样式版本
ScrollViewer 希望可以提供一个 滚动轴不需要鼠标悬浮也一直显示的样式版本
这样可以用于一直保持和外部其它UI元素对齐

### LINKED ISSUE #174: ScrollViewer.axaml 没找到 horizontalScrollBar 和 verticalScrollBar
Semi.Avalonia/Controls/ScrollViewer.axaml
241行
```
        <Style Selector="^:pointerover">
            <Style Selector="^ /template/ ScrollBar#horizontalScrollBar">
                <Setter Property="Opacity" Value="1" />
            </Style>
            <Style Selector="^ /template/ ScrollBar#verticalScrollBar">
                <Setter Property="Opacity" Value="1" />
            </Style>
        </Style>
```
没找到 horizontalScrollBar 和 verticalScrollBar

### PR DESCRIPTION
**Pull request by rabbitism**
Fix ScrollViewer styles
Add a new Theme `StaticScrollViewer` to make scrollbar visibility consistent with original design.
Add demo for ScrollViewer. 
Closes  #173 
Closes #174

### CODE REVIEW

**Comment by rabbitism** [comment]
@yangjieshao 大佬可以review一下吗？

**Comment by yangjieshao** [comment]
🐂 😙

**Comment by SmRiley** [comment]
Please tell me, if I want the default scrollbar style to be displayed directly internally, but also want to display it all the time, how should I set the style? It doesn't seem to work when I use this method
```xaml
<Style Selector="ScrollBar /template/ ScrollBar#PART_VerticalScrollBar">
      <Setter Property="Opacity"
              Value="1" />
  </Style>
```

**Comment by rabbitism** [comment]
@SmRiley Can you create a separate issue for this?

**Comment by SmRiley** [comment]
> @SmRiley Can you create a separate issue for this?

sure

**Pull request merged**
